apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitud-afiliacion-deployment
spec:
  replicas: 1  # Cambia este valor según tus necesidades de escalabilidad
  selector:
    matchLabels:
      app: solicitud-afiliacion
  template:
    metadata:
      labels:
        app: solicitud-afiliacion
    spec:
      hostAliases:                   # Agregamos la sección de hostAliases aquí
      - ip: "34.171.241.56"
        hostnames:
        - "kafka-svc"
      containers:
      - name: solicitud-afiliacion
      # image: johnmejia9887654321/incripcion-empleador-v5:latest  # Utiliza tu imagen Docker desde Docker Hub
        image: johnmejia9887654321/ms-empleador-rest-v1:latest  # Utiliza tu imagen Docker desde Docker Hub
        ports:
        - containerPort: 9094

---
apiVersion: v1
kind: Service
metadata:
  name: solicitud-afiliacion-service
spec:
  selector:
    app: solicitud-afiliacion
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  type: LoadBalancer  # Cambio aquí para utilizar NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: solicitud-afiliacion-svc
spec:
  selector:
    app: solicitud-afiliacion
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  type: ClusterIP  # Cambio aquí para utilizar NodePort


